### PR TITLE
Update one-dark.scss

### PR DESCRIPTION
**Pull request by adamgreenough**
Small contrast boost to bring colours in line with web version.

Still suggest there is more work to be done. I guess a font file is missing to boost the weight up a tad from 300. 

Per https://github.com/mjmlio/mjml-app/issues/310

### CODE REVIEW

**Comment by adamgreenough** [comment]
Before | After

Screenshot 2020-01-02 at 20 24 41

**Comment by adamgreenough** [comment]
Before | After
compare

**Comment by adamgreenough** [comment]
Thank you! :)

**Comment by meriadec** [comment]
Definitely important for accessibility. Also I think font-size could be increased by default.

@kmcb777 OK to merge?

**Pull request merged**
