### PR TITLE
Added SenderName routines and UI block

### PR DESCRIPTION
**Pull request by Mistra**
Here there's the barebone commit.
1st time I actually work with electron and still newbie with ES6, double check before merging!

- handleChangeInput = key => e => ... trims on every change, for the name it should be possible to put spaces before adding another word (not possible right now).

I could have implemented another "handleChangeSoftTrim(...)" or load the state and trim at the end of the operation but it looks a bit hacky. Plus I just want to focus on one at at time.

### CODE REVIEW

**Comment by meriadec** [comment]
Looks good to me for the code part, I just tested it and it's OK. 👍 

Can you do a  `yarn prettier` on the project? (remove `app/dist/bundle.js` and `app/main.js` before :) i guess they both need to be in a `.prettierignore`..)

**Comment by meriadec** [comment]
For the trim thing, yes we can totally have a `handleChangeSoftTrim`, or an additionnal "trim" argument to `handleChange` that take a `true` default.

**Comment by Mistra** [comment]
Hey, I've prettified it but I see no app/dist/bundle.js nor app/main.js, atleast... not in the develop branch

**Comment by meriadec** [comment]
Oh, they appear when you build. Don't mind.

Thanks !

**Pull request merged**
